# Generated by Django 6.1 on 2026-08-08 12:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(help_text='Format recommandé : +237XXXXXXXXX', max_length=20, unique=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('prestataire', 'Prestataire'), ('administrateur', 'Administrateur')], max_length=20)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('langue_preferee', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=2)),
                ('telephone_verifie', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acces', models.CharField(choices=[('support', 'Support / Modération'), ('super_admin', 'Super administrateur')], default='support', max_length=20)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'administrateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_administrateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_habituelle', models.CharField(blank=True, max_length=255)),
                ('nombre_demandes', models.PositiveIntegerField(default=0)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('annees_experience', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('piece_identite_recto', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('piece_identite_verso', models.ImageField(blank=True, null=True, upload_to='kyc/')),
                ('statut_kyc', models.CharField(choices=[('non_soumis', 'Non soumis'), ('en_attente', 'En attente de vérification'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='non_soumis', max_length=20)),
                ('kyc_commentaire', models.TextField(blank=True, help_text='Résultat/justification retourné par le service KYC')),
                ('note_moyenne', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('nombre_avis', models.PositiveIntegerField(default=0)),
                ('est_disponible', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(limit_choices_to={'role': 'prestataire'}, on_delete=django.db.models.deletion.CASCADE, related_name='profil_prestataire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestataire',
                'verbose_name_plural': 'Prestataires',
            },
        ),
    ]
