# Generated by Django 5.2.17 on 2026-08-29 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='selfie_avec_piece',
            field=models.ImageField(blank=True, help_text="Photo du visage du prestataire tenant sa pièce d'identité.", null=True, upload_to='kyc/'),
        ),
    ]
