# Generated by Django 5.2.17 on 2026-09-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_latitude_client_longitude'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Catégories de services proposées par ce prestataire.', related_name='prestataires', to='services.categorie'),
        ),
    ]
