# Generated by Django 5.2.17 on 2026-09-10 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_prestataire_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_fin_suspension',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='est_bloque',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='motif_sanction',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Litige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu')], default='ouvert', max_length=20)),
                ('type_sanction', models.CharField(choices=[('aucune', 'Aucune sanction'), ('suspension', 'Suspension temporaire'), ('blocage', 'Blocage définitif')], default='aucune', max_length=20)),
                ('duree_jours', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire_resolution', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('signale_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litiges_signales', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='litiges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litige',
                'verbose_name_plural': 'Litiges',
                'ordering': ['-date_creation'],
            },
        ),
    ]
