# Generated by Django 6.1 on 2026-08-08 12:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_structure', models.CharField(blank=True, max_length=150)),
                ('type_structure', models.CharField(choices=[('boutique', 'Boutique'), ('atelier', 'Atelier'), ('salon', 'Salon'), ('garage', 'Garage'), ('domicile', 'Domicile'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('adresse_texte', models.TextField(help_text="Description libre de l'adresse telle que fournie par l'utilisateur.")),
                ('quartier', models.CharField(blank=True, max_length=100)),
                ('ville', models.CharField(choices=[('douala', 'Douala'), ('yaounde', 'Yaoundé'), ('bafoussam', 'Bafoussam'), ('garoua', 'Garoua'), ('bamenda', 'Bamenda'), ('autre', 'Autre')], default='douala', max_length=20)),
                ('adresse_normalisee', models.TextField(blank=True, help_text='Adresse structurée générée par le module NLP.')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Coordonnées GPS (longitude, latitude).', null=True, srid=4326)),
                ('confiance_geocodage', models.FloatField(blank=True, help_text='Score de confiance (0-1) retourné par le module IA de géocodage.', null=True)),
                ('est_verifiee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='accounts.prestataire')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'indexes': [models.Index(fields=['ville', 'quartier'], name='geolocation_ville_ca25f4_idx')],
            },
        ),
    ]
