# Generated by Django 6.1 on 2026-08-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, help_text="Nom d'icône (ex : lucide-react-native) utilisé côté frontend.", max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie_parente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='services.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('prix_min', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prix_max', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('unite_prix', models.CharField(choices=[('forfait', 'Forfait'), ('heure', 'Par heure'), ('jour', 'Par jour'), ('metre_carre', 'Par m²')], default='forfait', max_length=20)),
                ('prix_suggere_ia', models.DecimalField(blank=True, decimal_places=0, help_text="Prix idéal suggéré par le module IA d'analyse prédictive des prix.", max_digits=10, null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.categorie')),
                ('localisation', models.ForeignKey(blank=True, help_text='Structure depuis laquelle ce service est proposé.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='geolocation.localisation')),
                ('prestataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.prestataire')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_originale', models.ImageField(upload_to='services/originales/')),
                ('image_amelioree', models.ImageField(blank=True, null=True, upload_to='services/ameliorees/')),
                ('est_principale', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'verbose_name': 'Image de service',
                'verbose_name_plural': 'Images de service',
                'ordering': ['-est_principale', 'date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['categorie', 'est_actif'], name='services_se_categor_6b12b6_idx'),
        ),
    ]
