# Generated by Django 6.1 on 2026-08-08 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAppelIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.PositiveSmallIntegerField(choices=[(1, 'NLP — Compréhension des adresses'), (2, "KYC — Vérification d'identité"), (3, 'Routage géospatial / ETA'), (4, 'Chatbot vocal'), (5, 'Rédaction assistée de contenu'), (6, "Retouche / amélioration d'image"), (7, 'Optimisation des prix'), (8, 'Moteur de recommandation'), (9, 'Suggestions de réponses automatiques')])),
                ('modele_utilise', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('tokens_entree', models.PositiveIntegerField(default=0)),
                ('tokens_sortie', models.PositiveIntegerField(default=0)),
                ('succes', models.BooleanField(default=True)),
                ('message_erreur', models.TextField(blank=True)),
                ('duree_ms', models.PositiveIntegerField(blank=True, help_text='Temps de réponse en millisecondes.', null=True)),
                ('date_appel', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'appel IA",
                'verbose_name_plural': 'Journal des appels IA',
                'ordering': ['-date_appel'],
                'indexes': [models.Index(fields=['module', 'date_appel'], name='ai_services_module_73bf09_idx')],
            },
        ),
    ]
