# Generated by Django 5.2.17 on 2026-08-11 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionVocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_question', models.FileField(upload_to='chatbot/questions/')),
                ('transcription', models.TextField()),
                ('reponse_texte', models.TextField()),
                ('audio_reponse', models.FileField(upload_to='chatbot/reponses/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_vocales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interaction vocale',
                'verbose_name_plural': 'Interactions vocales',
                'ordering': ['-date_creation'],
            },
        ),
    ]
