# Generated by Django 5.2.17 on 2026-09-10 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_utilisateur_date_fin_suspension_and_more'),
        ('messaging', '0003_conversations_entre_prestataires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('administrateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_admin', to='accounts.administrateur')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_avec_admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation avec administrateur',
                'verbose_name_plural': 'Conversations avec administrateur',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='MessageAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversationadmin')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_admin_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message administrateur',
                'verbose_name_plural': 'Messages administrateur',
                'ordering': ['date_envoi'],
            },
        ),
    ]
